
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels: #the labels can be removed because we will not be querying this service from
    #any other resource or selecting services from any other resource.
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80 #the port that the container exposes.
    targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app

